--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-18-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."STUDENT" 
   (	"HAKBEON" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.STUDENT
SET DEFINE OFF;
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('1','오세룡',25);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('10','이동준',17);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('3','박지호',20);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('11','박서준',19);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('12','김혜민',15);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('13','이범식',16);
Insert into C##SCOTT.STUDENT (HAKBEON,NAME,AGE) values ('14','오세룡',33);
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."STUDENT_PK" ON "C##SCOTT"."STUDENT" ("HAKBEON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."STUDENT" MODIFY ("HAKBEON" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("HAKBEON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
